"""共享常量定义"""

API_VERSION = "v1"
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# 默认 root 账号配置
DEFAULT_ROOT_USERNAME = "root"
DEFAULT_ROOT_PASSWORD = "root123"
DEFAULT_ROOT_DISPLAY_NAME = "系统管理员"

# Token 配置
ACCESS_TOKEN_EXPIRE_MINUTES = 60
REFRESH_TOKEN_EXPIRE_DAYS = 7
